# Generated by Django 3.1.1 on 2020-11-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='pics')),
                ('csv_tag', models.CharField(max_length=50)),
                ('csv_flag', models.CharField(max_length=50)),
            ],
        ),
    ]
